### ISSUE TITLE
No scheduled notification when Android App is killed. 

### ISSUE THREAD

**Issue by Mataboge** [thudugala/Plugin.LocalNotification#98] opened 2020-07-23 09:59 UTC
**Describe the bug**
When scheduling a notification at a specific time and then killing the App before that time arrives, the notification does not pop up on Android. When the application is on the foreground (or even running in the background) it seem to be working fine.  

iOS seems to be working fine.

**To Reproduce**
1. Schedule a notification
2. kill the App
3. Wait for the time to arrive
4. No pop up

**Expected behavior**
The notification should appear.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10, Visual Studio 2019 16.5

**Smartphone (please complete the following information):**
 - Device: Huawei p20 (real device) and Pixel 3 Emulator
 - OS: Android 9
- Targeting Android 10

**Comment by thudugala** [comment] 2020-07-23 20:29
@Mataboge Can you try on a real device like Samsung

**Comment by Mataboge** [comment] 2020-07-24 21:33
I have changed the way I close the App in the meantime - it seems to be responding well, I will test on a Samsung device soon and see.

**Comment by Mataboge** [comment] 2020-07-24 21:39
@thudugala: Weirdly enough, the Notification tapped event method is not raised when tapping. The App does open normally when you tap the notification, but it does not go through that method. I have placed the method exactly as described in the documentation page in App.xaml.cs

`    private void Current_NotificationTapped(NotificationTappedEventArgs e)
        {
            Debug.Print("notification has been tapped.");
            Debug.Print("The data =  " + e.Data);
        }
`

**Comment by thudugala** [comment] 2020-07-25 03:01
@Mataboge can you attach a sample project

**Comment by jmseatssoftware** [comment] 2020-08-28 09:20
Hi! Same behavior here on Moto Z3 / Android 8.1 phone. It can be easily reproducible with the demo App (no scheduled notifications when the app is killed). I use Plugin.Notifications since more than one year and realized this started happening when changed the target from Android 9 to Android 10. I have used the "Migrate to AndroidX" feature of Visual Studio 2019 v16.7.2

**Comment by maciejpawlo** [comment] 2020-08-31 14:36
@Mataboge https://github.com/thudugala/Plugin.LocalNotification/issues/99#issuecomment-683816111 hope it could be helpful for you

**Comment by Mataboge** [comment] 2020-09-01 09:56
@maciejpawlo Thank you very much for this, This seems to be exactly what happened in my case since I have a custom splash screen as described in your link. How did you then trigger the event? do you trigger it in the splashcreen activity?

**Comment by maciejpawlo** [comment] 2020-09-01 10:15
@Mataboge I did a little workaround. I had tried triggering event in splashcreen activity, but it didn't work so I changed the way how the splashscreen shows (don't know if its a 'proper' way, but it works). I had disabled my SplashScreen activity (set the MainActivity MainLauncher prop back to 'true'). Then in styles.xml I set the property of android:windowBackground to my .xml splashcreen file. The drawback of that workaround is that you have to change manually backround color in all of your .xml Pages files.

**Comment by jigneshbodarya** [comment] 2020-09-23 12:20
I'm experience the same issue, Any update here?

**Comment by MarcoNarde** [comment] 2020-09-29 14:46
Someone solved the issue?

**Comment by AviatorRodent** [comment] 2020-10-01 22:26
I have the same problem. Location notifications are being delivered without issue on iOS (with app in foreground, background, and killed). For android however, I'm only getting the notifications if the app is in foreground or background NOT when killed.

Any scheduled notifications due to be received while the app was closed, appear to be delivered when the app is opened again.

**Comment by jigneshbodarya** [comment] 2020-10-12 09:47
Any updates?

**Comment by AviatorRodent** [comment] 2020-10-26 11:25
Any update on this @thudugala? Do you have an idea as to when it might be fixed?

**Comment by thudugala** [comment] 2020-12-17 20:35
Fixed in v5.20

**Closed by thudugala** 2020-12-17 20:35 UTC
Labels: bug
